package remoteinstall

import (
	"strings"
	"text/template"
)

// BinDir and BinPath are where the remote binary lands. `~/.local/bin` is on
// the default PATH of every distribution sonar targets and needs no root, which
// is the whole point: `sonar remote install` must not ask for sudo.
const (
	BinDir  = "$HOME/.local/bin"
	BinPath = "$HOME/.local/bin/sonar"
	// BinDisplay is BinPath as a person reads it, and as the result and the
	// stream's end report it: $HOME is the remote shell's business, not a
	// client's.
	BinDisplay = "~/.local/bin/sonar"

	// UnitPath is the systemd *user* unit. A user unit runs as the SSH user,
	// sees that user's processes, and needs no privileges.
	UnitDir  = "$HOME/.config/systemd/user"
	UnitPath = "$HOME/.config/systemd/user/sonar.service"
)

// Marker prefixes the progress lines the remote script prints on stdout. The
// local side turns each into one `remote.install` stream chunk; anything else
// the remote prints becomes a chunk with step "remote".
const (
	Marker      = "sonar-install"
	ErrorMarker = "sonar-install-error"
)

// The steps a chunk's `step` field can carry. The remote script emits
// download, verify, extract, install, service, linger and done; the local side
// adds connect, detect, resolve and check around them.
const (
	StepConnect = "connect"
	StepDetect  = "detect"
	StepResolve = "resolve"

	StepDownload = "download"
	StepVerify   = "verify"
	StepExtract  = "extract"
	StepInstall  = "install"
	StepService  = "service"
	StepLinger   = "linger"
	StepDone     = "done"

	StepCheck  = "check"
	StepRemote = "remote"
)

// The service modes the `service` chunk reports, and Result.Service carries.
const (
	ServiceSystemd  = "systemd"
	ServiceDetached = "detached"
	ServiceNone     = "none"
)

// Unit is the systemd user unit the install writes.
//
// KillMode=process is deliberate: the daemon starts a group's services as
// detached children, and they live in the unit's cgroup whatever setsid does.
// With the default control-group kill mode, `systemctl --user restart sonar`
// during an upgrade would take every service the user had started down with it.
const Unit = `[Unit]
Description=sonar daemon
Documentation=https://github.com/raskrebs/sonar
After=network.target

[Service]
Type=simple
ExecStart=%h/.local/bin/sonar serve
Environment=PATH=%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Restart=on-failure
RestartSec=2
KillMode=process

[Install]
WantedBy=default.target
`

// scriptParams is what the template renders. Every value is produced by this
// package, never by the remote: the download URL and the expected sha256 are
// resolved from the release before the script is written, so the remote host
// verifies against a checksum that travelled over the local machine's TLS.
type scriptParams struct {
	Version  string
	Platform string
	Asset    string
	URL      string
	SHA256   string
	Service  bool
	Unit     string
	BinDir   string
	BinPath  string
	UnitDir  string
	UnitPath string
	Marker   string
	ErrMark  string
}

var scriptTemplate = template.Must(template.New("install").Parse(`#!/bin/sh
# Generated by ` + "`sonar remote install`" + `: sonar {{.Version}} for {{.Platform}}.
set -eu

say() { printf '{{.Marker}}\t%s\t%s\n' "$1" "$2"; }
die() { printf '{{.ErrMark}}\t%s\n' "$1" >&2; exit 1; }

BIN_DIR="{{.BinDir}}"
BIN="{{.BinPath}}"
ASSET="{{.Asset}}"
URL="{{.URL}}"
SHA256="{{.SHA256}}"

if command -v curl >/dev/null 2>&1; then
	fetch() { curl -fsSL -o "$2" -- "$1"; }
elif command -v wget >/dev/null 2>&1; then
	fetch() { wget -q -O "$2" -- "$1"; }
else
	die "neither curl nor wget is installed on this host"
fi

if command -v sha256sum >/dev/null 2>&1; then
	verify() { sha256sum -c "$1" >/dev/null; }
elif command -v shasum >/dev/null 2>&1; then
	verify() { shasum -a 256 -c "$1" >/dev/null; }
else
	die "neither sha256sum nor shasum is installed on this host"
fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/sonar-install.XXXXXX")
trap 'rm -rf "$TMP"' EXIT HUP INT TERM

say download "$URL"
fetch "$URL" "$TMP/$ASSET" || die "downloading $URL failed"

say verify "$SHA256"
printf '%s  %s\n' "$SHA256" "$ASSET" >"$TMP/$ASSET.sha256"
(cd "$TMP" && verify "$ASSET.sha256") || die "$ASSET does not match the sha256 the release publishes"

say extract "$ASSET"
tar -xzf "$TMP/$ASSET" -C "$TMP" sonar || die "extracting sonar from $ASSET failed"

say install "$BIN"
mkdir -p "$BIN_DIR"
cp "$TMP/sonar" "$BIN.new"
chmod 755 "$BIN.new"
mv -f "$BIN.new" "$BIN"
{{if .Service}}
if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
	"$BIN" daemon stop >/dev/null 2>&1 || true
	mkdir -p "{{.UnitDir}}"
	cat >"{{.UnitPath}}" <<'SONAR_UNIT'
{{.Unit}}SONAR_UNIT
	systemctl --user daemon-reload || die "systemctl --user daemon-reload failed"
	systemctl --user enable sonar.service >/dev/null 2>&1 || die "systemctl --user enable sonar.service failed"
	systemctl --user restart sonar.service || die "systemctl --user restart sonar.service failed"
	say service systemd
	if command -v loginctl >/dev/null 2>&1 && [ "$(loginctl show-user "$(id -un)" --property=Linger --value 2>/dev/null || echo no)" != "yes" ]; then
		say linger "sudo loginctl enable-linger $(id -un)"
	fi
else
	"$BIN" daemon restart || die "starting the daemon failed"
	say service detached
fi
{{else}}
say service none
{{end}}`))

// Script renders the shell script the install pipes to `sh -s` on the remote
// host. It is a single POSIX-sh program with no bashisms, because a remote
// login shell may be dash, ash or ksh.
func Script(p scriptParams) string {
	p.Marker = Marker
	p.ErrMark = ErrorMarker
	p.BinDir = BinDir
	p.BinPath = BinPath
	p.UnitDir = UnitDir
	p.UnitPath = UnitPath
	p.Unit = Unit
	var b strings.Builder
	if err := scriptTemplate.Execute(&b, p); err != nil {
		// The template is a constant and every field is a string: this cannot
		// fail at runtime.
		panic("remoteinstall: rendering the install script: " + err.Error())
	}
	return b.String()
}
