#!/bin/sh
# Generated by `sonar remote install`: sonar v0.6.0 for linux/amd64.
set -eu

say() { printf 'sonar-install\t%s\t%s\n' "$1" "$2"; }
die() { printf 'sonar-install-error\t%s\n' "$1" >&2; exit 1; }

BIN_DIR="$HOME/.local/bin"
BIN="$HOME/.local/bin/sonar"
ASSET="sonar_linux_amd64.tar.gz"
URL="https://github.com/raskrebs/sonar/releases/download/v0.6.0/sonar_linux_amd64.tar.gz"
SHA256="f39d4a5bae986a4cefcd927680b4b2f6bfa065cf488baffce40e8af39f59e909"

if command -v curl >/dev/null 2>&1; then
	fetch() { curl -fsSL -o "$2" -- "$1"; }
elif command -v wget >/dev/null 2>&1; then
	fetch() { wget -q -O "$2" -- "$1"; }
else
	die "neither curl nor wget is installed on this host"
fi

if command -v sha256sum >/dev/null 2>&1; then
	verify() { sha256sum -c "$1" >/dev/null; }
elif command -v shasum >/dev/null 2>&1; then
	verify() { shasum -a 256 -c "$1" >/dev/null; }
else
	die "neither sha256sum nor shasum is installed on this host"
fi

TMP=$(mktemp -d "${TMPDIR:-/tmp}/sonar-install.XXXXXX")
trap 'rm -rf "$TMP"' EXIT HUP INT TERM

say download "$URL"
fetch "$URL" "$TMP/$ASSET" || die "downloading $URL failed"

say verify "$SHA256"
printf '%s  %s\n' "$SHA256" "$ASSET" >"$TMP/$ASSET.sha256"
(cd "$TMP" && verify "$ASSET.sha256") || die "$ASSET does not match the sha256 the release publishes"

say extract "$ASSET"
tar -xzf "$TMP/$ASSET" -C "$TMP" sonar || die "extracting sonar from $ASSET failed"

say install "$BIN"
mkdir -p "$BIN_DIR"
cp "$TMP/sonar" "$BIN.new"
chmod 755 "$BIN.new"
mv -f "$BIN.new" "$BIN"

if command -v systemctl >/dev/null 2>&1 && systemctl --user show-environment >/dev/null 2>&1; then
	"$BIN" daemon stop >/dev/null 2>&1 || true
	mkdir -p "$HOME/.config/systemd/user"
	cat >"$HOME/.config/systemd/user/sonar.service" <<'SONAR_UNIT'
[Unit]
Description=sonar daemon
Documentation=https://github.com/raskrebs/sonar
After=network.target

[Service]
Type=simple
ExecStart=%h/.local/bin/sonar serve
Environment=PATH=%h/.local/bin:/usr/local/bin:/usr/bin:/bin
Restart=on-failure
RestartSec=2
KillMode=process

[Install]
WantedBy=default.target
SONAR_UNIT
	systemctl --user daemon-reload || die "systemctl --user daemon-reload failed"
	systemctl --user enable sonar.service >/dev/null 2>&1 || die "systemctl --user enable sonar.service failed"
	systemctl --user restart sonar.service || die "systemctl --user restart sonar.service failed"
	say service systemd
	if command -v loginctl >/dev/null 2>&1 && [ "$(loginctl show-user "$(id -un)" --property=Linger --value 2>/dev/null || echo no)" != "yes" ]; then
		say linger "sudo loginctl enable-linger $(id -un)"
	fi
else
	"$BIN" daemon restart || die "starting the daemon failed"
	say service detached
fi
